config/routes.rb
Rails.application.routes.draw do
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'top/main'
  post 'top/login'
  root 'top#main'
  get 'top/logout'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        if session[:login_uid]
            render "main"
        else
            render "login"
        end
    end
    
    def login
        user = User.find_by(uid: params[:uid])
        if user and BCrypt::Password.new(user.pass) == params[:pass]
            session[:login_uid] = params[:uid]
            redirect_to top_main_path
        else
            render "error", status: 422
        end
    end
    
    def logout
        session.delete(:login_uid)
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end

  def create
    signup_password = BCrypt::Password.create(params[:user][:pass])
    #logger.debug signup_password
    u = User.new(uid: params[:user][:uid], pass: signup_password)
    u.save
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
ログイン失敗

<p>
    <%= link_to '戻る', top_logout_path %>
</p>

app/views/top/login.html.erb
<%= form_with url: '/top/login', method: :post, local: true do |f| %>
<%= f.label :uid, 'ユーザーID' %>
<%= f.text_field :uid %>
<%= f.label :pass, 'パスワード' %>
<%= f.password_field :pass %>
<%= f.submit '登録' %>
<% end %>

<%= link_to "ユーザ登録", new_user_path %>
<%= link_to "ユーザ一覧", users_path %>

app/views/top/main.html.erb
ログイン中・・・


<p>
    <%= link_to 'ログアウト', top_logout_path %>
</p>

app/views/users/index.html.erb
<% @users.each do |e| %>
uid: <%= e.uid %>, pass: <%= e.pass%><br>
<% end %>

<%= link_to "新規追加", new_user_path %>

<%= link_to "ログイン", root_path %>

app/views/users/new.html.erb
<%= form_with model: @user do |f| %>
<%= f.label :uid, 'UID' %>
<%= f.text_field :uid %>
<%= f.label :pass, 'PASS' %>
<%= f.password_field :pass %>
<%= f.submit '登録' %>
<% end %>